server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:5501/.well-known/jwks.json
database:
  url: mongodb+srv://root:root@cluster0.ngdanu1.mongodb.net/order_db?authSource=admin&w=1
frontend:
  clientUI: http://localhost:3000
  adminUI: http://localhost:5173
kafka:
  broker: localhost:9092

